# @package _global_
core_lib:
  notification_core_lib:
    cache:
      notification:
        type: memcached
        url:
          host: ${oc.env:MEMCACHED_HOST}
          port: ${oc.env:MEMCACHED_PORT}
  data:
    sqlalchemy:
      _target_: core_lib.connection.sql_alchemy_connection_factory.SqlAlchemyConnectionFactory
      config:
        log_queries: false
        create_db: false
        session:
          pool_recycle: 3200
          pool_pre_ping: false
        url:
          protocol: postgresql
          username: ${oc.env:POSTGRES_USER}
          password: ${oc.env:POSTGRES_PASSWORD}
          host: ${oc.env:POSTGRES_HOST}
          port: ${oc.env:POSTGRES_PORT}
          file: ${oc.env:POSTGRES_DB}
  alembic:
    version_table: notification_alembic_version
